### ISSUE TITLE
Project: Voxel model upsampling

### ISSUE THREAD

**Issue by dkurt** [dkurt/halide_riscv#11]
## Voxel model upsampling

- [x] Выполнена подготовка проекта
- [x] Написан алгоритм на Halide и запущен на x86 (https://github.com/dkurt/halide_riscv/pull/23)
- [x] Алгоритм запущен на RISC-V без регрессии, сгенерирован скалярный код (PR)
- [ ] Алгоритм векторизован под RISC-V без регрессии, сгенерирован векторизованный код (PR)
- [ ] (опционально) Получилось применить автопланировщик, сравнить с собственной векторизацией
- [ ] Подготовить 1-2 слайда о своей работе

Реализовать метод увеличения разрешения для трехмерной voxel модели, используя метод обратной свертки.

reference code: https://gist.github.com/dkurt/d9dfa96c0f4e9a09d8018351a9f08ef4

<details>
<summary>Скрипт для визуализации</summary>

```python
import matplotlib.pyplot as plt
import numpy as np
import cv2 as cv

slices = []
for i in range(1, 73):
    slices.append(cv.imread(f"test/image{i:04}.png", cv.IMREAD_UNCHANGED))
    slices[-1] = cv.rotate(slices[-1], cv.ROTATE_90_CLOCKWISE)
    slices[-1][...,3] = slices[-1][...,3] > 0

img = np.stack(slices, axis=2)

x, y, z = np.indices((img.shape[0] + 1, img.shape[1] + 1, img.shape[2] + 1))
is_visible = img[...,3]

img = img.astype(np.float32) / 255
colors = img[..., [2, 1, 0]]

ax = plt.figure().add_subplot(projection='3d')
ax.voxels(x, y, z, is_visible,
          facecolors=colors,
          edgecolors=np.clip(2*colors - 0.5, 0, 1),  # brighter
          linewidth=0.5)
ax.set(xlabel='x', ylabel='y', zlabel='z')
ax.set_aspect('equal')

plt.savefig("img.png")
```

</details>

Воксельная модель по слоям (в виде .png изображений): [test.zip](https://github.com/dkurt/halide_riscv/files/14138126/test.zip)

**Comment by dkurt** [comment]
```cpp
cv::Mat voxels({num_images, 3, rows, cols}, CV_8U);
for (int i = 0; i < num_images; ++i) {
  cv::Mat img = imread("image_i.png");
  std::vector<cv::Mat> colors(3);
  colors[0] = Mat({rows, cols}, CV_8U, voxels.at<uchar>(i, 0));
  colors[1] = Mat({rows, cols}, CV_8U, voxels.at<uchar>(i, 2));
  colors[2] = Mat({rows, cols}, CV_8U, voxels.at<uchar>(i, 3));
  cv::split(img, colors);
}
```

**Comment by SirTruber** [comment]
![image](https://github.com/dkurt/halide_riscv/assets/62519734/a38ff461-4050-406a-a327-878f31b023ea)
При make для x86 почему-то подцепляется библиотека линейной алгебры Eigen, там немного другие функции. rv64 собирается. Как поправить?

**Comment by dkurt** [comment]
try add `-DWITH_EIGEN=OFF` to https://github.com/dkurt/halide_riscv/blob/main/CMakeLists.txt (OpenCV part with `ExternalProject_Add`)
