### ISSUE TITLE
Project: Julia set fractal

### ISSUE THREAD

**Issue by dkurt** [dkurt/halide_riscv#9]
## Julia set fractal

- [x] Выполнена подготовка проекта
- [x] Написан алгоритм на C++ и запущен на x86 (https://github.com/dkurt/halide_riscv/pull/14)
- [x] Написан алгоритм на Halide и запущен на x86 (https://github.com/dkurt/halide_riscv/pull/14)
- [x] Алгоритм запущен на RISC-V без регрессии, сгенерирован скалярный код (https://github.com/dkurt/halide_riscv/pull/18)
- [x] Алгоритм векторизован под RISC-V без регрессии, сгенерирован векторизованный код (PR)
- [ ] (опционально) Получилось применить автопланировщик, сравнить с собственной векторизацией
- [ ] Подготовить 1-2 слайда о своей работе

https://en.wikipedia.org/wiki/Julia_set

![fractal](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Julia_set%2C_plotted_with_Matplotlib.svg/1280px-Julia_set%2C_plotted_with_Matplotlib.svg.png)

**Comment by IgorErin** [comment]
I take this.

**Comment by dkurt** [comment]
@IgorErin , напишите про скорость на x86 (halide vs reference) и добавьте новым PR генерацию под RISC-V
